### ISSUE TITLE
How can I improve my site?

### ISSUE THREAD

**Issue by MastooraTurkmen** [MastooraTurkmen/Simple-Card#3]
I need your feedback to improve my site. Thank you :)

**Comment by developedbyjk** [comment]
You site look amazing🤩 i like the color combination ✨... You can add random image with `https://source.unsplash.com/random` and random content. So whenever it load it will give random images🖼 🐦 hope it helps😇

**Comment by MastooraTurkmen** [comment]
Thank you so much for your nice feedback. I will use it and improve it, too.
